---
- hosts: webapp
  tasks: 
  - name: "Install httpd package"
    yum: 
        name: httpd
        state: latest
  - name: "check httpd service status"
    service: 
        name: httpd
        state: started
